---
general:
  name: sparkbench

kubernetes:
  ip: 192.168.185.2
  port: 6443
  num_nodes: 13

scala:
  version: 2.12.18
  version_short: 2.12

docker:
  username: lkmschulz2
  version: latest

services:
  ip: 192.168.1.104
  minio:
    ports:
      core: 9000
      console: 9001
    mnt: /mnt/nvme0n1/lennart/sparkbench-data/minio
    access_key: user
    secret_key: password
  hive:
    port: 9083
    mnt: /mnt/nvme0n1/lennart/sparkbench-data/warehouse
  postgres:
    mnt: /mnt/nvme0n1/lennart/sparkbench-data/postgres
    user: hive
    password: password
    db: metastore_db
  influx:
    port: 8086
    mnt: /mnt/nvme0n1/lennart/sparkbench-data/influx
    organization: sparkbench
    user: admin
    password: password
    token: token
  
templates:
  path: ./templates
  disclaimer: "WARNING: Edits in this file will be overwritten when applying the template configurations! Edit the template instead."
  targets:
    spark: 
      src: spark-defaults.conf
      dst: ./spark-defaults.conf
    services: 
      src: docker-compose.yaml
      dst: ./docker/docker-compose.yaml
    telegraf:
      src: telegraf.conf
      dst: ./scripts/telegraf/telegraf.conf
    hive:
      src: hive-site.xml
      dst: ./docker/hive-site.xml
    dockerfile:
      src: Dockerfile
      dst: ./docker/Dockerfile
    sbt:
      src: build.sbt
      dst: ./build.sbt

...
