apiVersion: v1
kind: Pod
metadata:
  name: driver
spec:
  containers:
  - name: {{general.name}}
    image: {{docker.username}}/{{general.name}}:{{docker.version}}
    resources:
      requests:
        ephemeral-storage: "30G"
      limits:
        ephemeral-storage: "40G"
  nodeSelector:
    driver-node: true
  tolerations:
  - key: role
    value: driver
    operator: Equal
    effect: NoSchedule
  imagePullSecrets: 
  - name: regcred
